### ISSUE TITLE
Services stats not showing

### ISSUE THREAD

**Issue by asjongers** [big-data-europe/ember-swarm-ui-engine#5] opened 2017-11-20 12:27 UTC
During today's demo, after creating a second pipeline from the same stack and starting it then checking some stats, nothing was ever shown (at least not until I force refreshed the page). 

I have not been able to reproduce this behavior afterwards though.

**Comment by fr0gs** [comment] 2017-11-20 12:29
As a reminder for the future, it may be a race condition on the swarm-logger since when creating a pipeline, you are cloning it the first time before running.

**Comment by fr0gs** [comment] 2017-11-21 10:24
I have not been able to reproduce this issue after several tries, it works for several pipelines running at the same time. I suspect it is linked to the fix of this commit: https://github.com/big-data-europe/app-bdi-ide/commit/18aa6d656738ce155e61480c662d6daebd16e58f I also implemented. 
Normally if the swarm-admin fails, everything tends to fall apart. I am closing this issue and we may reopen it in the future.

**Closed as completed by fr0gs** 2017-11-21 10:24 UTC
